<p><img alt="Colaboratory logo" height="140px" src="https://upload.wikimedia.org/wikipedia/commons/archive/f/fb/20161010213812%21Escudo-UdeA.svg" align="left" hspace="10px" vspace="0px"></p>

# **Curso de bases para AI - Universidad de Antioquia**


El presente curso hace parte del centro de Big Data de la facultad de ciencias exactas y naturales (FCEN) de la Universidad de Antioquia.

\

El curso será dictado en 16 sesiones o clases de 4 horas los días sábado en las instalaciones de la universidad. Para un total de dededicación temporal de 64 horas. El curso cuenta con los siguientes módulos:

1. Bases matemáticas y de programación. (10H)
2. Bases de Python. (19H)
3. Bases de R. (13H)
4. Procesamiento de datos. (22H)

#**Aviso**

Para aquelllos interesados libros de Machine Learning y análisis de datos, Springer ha liberado 65 de ellos, a los cuales pueden acceder mediante el [este link](https://towardsdatascience.com/springer-has-released-65-machine-learning-and-data-books-for-free-961f8181f189).

# **El modulo Numpy**

Numpy es un paquete fundamental para el trabajo científico en python:
* Contiene Funciones, módulos, clases y cierto tipo especial de datos. 
* Permite el manejo de Arrays Multidimensionales. 
* Contiene Funciones sofisticadas y optimizadas. Permite incorporar códigos en C/C++ o fortran. 
* Contiene un paquete de álgebra lineal y permite hacer cálculos estadísticos, ajustes, interpolación entre otras.


> El tipo de dato mas importante en numpy es el **array**. El array es un tipo de dato, formado a partir de otro tipo de datos mas sencillos y que estan ordenados en una secuencia definida, en ese sentido es muy similar a una lista o tupla, pero a diferencia de estos, un array solo admite un tipo de dato.


## Crear un array con datos nativos 

Un array puede ser creado mediante el uso de datos nativos de python (listas, tuplas,datos
básicos) usando la función **numpy.array()**:

```python
numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)¶
```
Donde podemos especificar el tipo de datos con *dtype*, el orden con *order* (esto hace referencia el modo "C", por filas, o "F", por columnas, para el diseño de memoria del arreglo. Generalmente se deja en "K" para que automaticamente escoja la mejor opción), la dimensión miníma puede establecerse con con *ndmin*. 

In [3]:
import numpy as np
arreglo = np.array([1,2,3])
print("Clase:",type(arreglo))
methods = [m for m in dir(arreglo) if not m.startswith('__') and callable(getattr(arreglo, m))]
attr = [m for m in dir(arreglo) if not m.startswith('__') and not callable(getattr(arreglo, m))]
print("Atributos:", attr)
print("Métodos:",methods)

Clase: <class 'numpy.ndarray'>
Atributos: ['T', 'base', 'ctypes', 'data', 'dtype', 'flags', 'flat', 'imag', 'itemsize', 'nbytes', 'ndim', 'real', 'shape', 'size', 'strides']
Métodos: ['all', 'any', 'argmax', 'argmin', 'argpartition', 'argsort', 'astype', 'byteswap', 'choose', 'clip', 'compress', 'conj', 'conjugate', 'copy', 'cumprod', 'cumsum', 'diagonal', 'dot', 'dump', 'dumps', 'fill', 'flatten', 'getfield', 'item', 'itemset', 'max', 'mean', 'min', 'newbyteorder', 'nonzero', 'partition', 'prod', 'ptp', 'put', 'ravel', 'repeat', 'reshape', 'resize', 'round', 'searchsorted', 'setfield', 'setflags', 'sort', 'squeeze', 'std', 'sum', 'swapaxes', 'take', 'tobytes', 'tofile', 'tolist', 'tostring', 'trace', 'transpose', 'var', 'view']


In [10]:
def niceprint(array):
  return np.array2string(array).replace('[',' ').replace(']',' ')

def attr_array(array):
  print("El arreglo es: ", array)
  print("Las dimensiones del arreglo son: ",array.shape,end=" ")
  print("cs,s,r,c --> recordar (conjunto,corte,fila,columna)")
  print("El número de dimensiones del arreglo es: ", array.ndim)
  print("El número de elementos del arreglo es: ", array.size)
  print("El tamaño de un elemento del arreglo es: ", array.itemsize,'bytes')
  print("El tamaño total de elementos del arreglo es: ", array.nbytes,'bytes')
  print("El tipo de elementos del arreglo es: ", array.dtype)
  print("Parte real del arreglo es: ", array.real)
  print("Parte imaginaria del arreglo es: ", array.imag)
  print("Su transpuesta es: ", array.T)
  print()

arreglo = np.array([1,2,3])
attr_array(arreglo)

El arreglo es:  [1 2 3]
Las dimensiones del arreglo son:  (3,) cs,s,r,c --> recordar (conjunto,corte,fila,columna)
El número de dimensiones del arreglo es:  1
El número de elementos del arreglo es:  3
El tamaño de un elemento del arreglo es:  8 bytes
El tamaño total de elementos del arreglo es:  24 bytes
El tipo de elementos del arreglo es:  int64
Parte real del arreglo es:  [1 2 3]
Parte imaginaria del arreglo es:  [0 0 0]
Su transpuesta es:  [1 2 3]



In [11]:
arreglo = np.array([1,2.0,3+3j])
attr_array(arreglo)

El arreglo es:  [1.+0.j 2.+0.j 3.+3.j]
Las dimensiones del arreglo son:  (3,) cs,s,r,c --> recordar (conjunto,corte,fila,columna)
El número de dimensiones del arreglo es:  1
El número de elementos del arreglo es:  3
El tamaño de un elemento del arreglo es:  16 bytes
El tamaño total de elementos del arreglo es:  48 bytes
El tipo de elementos del arreglo es:  complex128
Parte real del arreglo es:  [1. 2. 3.]
Parte imaginaria del arreglo es:  [0. 0. 3.]
Su transpuesta es:  [1.+0.j 2.+0.j 3.+3.j]



In [12]:
arreglo = np.array([1,2,487],dtype="str")
attr_array(arreglo)

El arreglo es:  ['1' '2' '487']
Las dimensiones del arreglo son:  (3,) cs,s,r,c --> recordar (conjunto,corte,fila,columna)
El número de dimensiones del arreglo es:  1
El número de elementos del arreglo es:  3
El tamaño de un elemento del arreglo es:  12 bytes
El tamaño total de elementos del arreglo es:  36 bytes
El tipo de elementos del arreglo es:  <U3
Parte real del arreglo es:  ['1' '2' '487']
Parte imaginaria del arreglo es:  ['' '' '']
Su transpuesta es:  ['1' '2' '487']



In [15]:
arreglo = np.array([[1,2],[3,4],[5,6]],dtype=np.int32)
attr_array(arreglo)

El arreglo es:  [[1 2]
 [3 4]
 [5 6]]
Las dimensiones del arreglo son:  (3, 2) cs,s,r,c --> recordar (conjunto,corte,fila,columna)
El número de dimensiones del arreglo es:  2
El número de elementos del arreglo es:  6
El tamaño de un elemento del arreglo es:  4 bytes
El tamaño total de elementos del arreglo es:  24 bytes
El tipo de elementos del arreglo es:  int32
Parte real del arreglo es:  [[1 2]
 [3 4]
 [5 6]]
Parte imaginaria del arreglo es:  [[0 0]
 [0 0]
 [0 0]]
Su transpuesta es:  [[1 3 5]
 [2 4 6]]



### Ejercicios 

1.   Cree un arreglo de tres dimensiones usando la lista `[1,2,3]`
2.   Cree un arreglo de shape `(2, 5, 3)` 



In [0]:
#@title Vea la solución **aquí**

#arreglo1 = np.array([1,2,3],ndmin=3)
#print(arreglo1.ndim)
#lista1d = [1,2,3]
#lista2d = [lista1d]*5
#lista3d = [lista2d]*2
#arreglo2 = np.array(lista3d)
#print(arreglo2.shape)


## Funciones de Numpy para crear arreglos

* ```python 
arange([start],[stop],[step],dtype=None)
```


In [17]:
arreglo1 = np.arange(0,3,0.5)
print("Desde 1.0 a 2.0 de a 0.1, el 2 no se toma:",arreglo1)

Desde 1.0 a 2.0 de a 0.1, el 2 no se toma: [0.  0.5 1.  1.5 2.  2.5]


* ```python 
linspace(start,stop,num=50,endpoint=True,retstep=False,axis=0)
``` 


In [19]:
arreglo2 = np.linspace(0,12,10)
print("10 valores desde 0 a 12, tomando el 12: ", arreglo2)

10 valores desde 0 a 12, tomando el 12:  [ 0.          1.33333333  2.66666667  4.          5.33333333  6.66666667
  8.          9.33333333 10.66666667 12.        ]


In [20]:
arreglo3 = np.linspace(0,10,10,endpoint=False)
print("10 valores desde 0 a 10, sin tomar el 10: ", arreglo3)

10 valores desde 0 a 10, sin tomar el 10:  [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [21]:
info_arreglo = np.linspace(-2,10,10,endpoint=False,retstep=True)
print("10 valores desde -2 a 10, sin tomar el 10 y el paso usado (tupla): \n", info_arreglo)

10 valores desde -2 a 10, sin tomar el 10 y el paso usado (tupla): 
 (array([-2. , -0.8,  0.4,  1.6,  2.8,  4. ,  5.2,  6.4,  7.6,  8.8]), 1.2)


In [22]:
arreglo4 = np.linspace([0,2],[1,3],10)
print("Un arreglo multidimensional de",arreglo4.shape,": \n", arreglo4)

Un arreglo multidimensional de (10, 2) : 
 [[0.         2.        ]
 [0.11111111 2.11111111]
 [0.22222222 2.22222222]
 [0.33333333 2.33333333]
 [0.44444444 2.44444444]
 [0.55555556 2.55555556]
 [0.66666667 2.66666667]
 [0.77777778 2.77777778]
 [0.88888889 2.88888889]
 [1.         3.        ]]


In [0]:
arreglo5 = np.linspace([0,2],[1,3],10,axis=1)
print("Un arreglo multidimensional de",arreglo5.shape,": \n", arreglo5)

Un arreglo multidimensional de (2, 10) : 
 [[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
  0.66666667 0.77777778 0.88888889 1.        ]
 [2.         2.11111111 2.22222222 2.33333333 2.44444444 2.55555556
  2.66666667 2.77777778 2.88888889 3.        ]]


* ```python 
ones(shape,dtype=None)
```
*```python  
zeros(shape, dtype=float)
```

In [23]:
arreglo6 = np.ones((4,6))
print("Un arreglo de 1 multidimensional de",arreglo6.shape,": \n", arreglo6)

Un arreglo de 1 multidimensional de (4, 6) : 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [24]:
arreglo7 = np.zeros((2,2,6))
print("Un arreglo de 0 multidimensional de",arreglo7.shape,": \n", arreglo7)

Un arreglo de 0 multidimensional de (2, 2, 6) : 
 [[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


### Ejercicios

1. Cree un arreglo de 10 valores desde 0 a 50 en una columna y en la otra desde -500 a 500. 

2. Cree un arreglo de ceros de 4 dimensiones. 

In [0]:
#@title Vea la solución **aquí**

#arreglo1 = np.linspace([0,-500],[50,500],10)
#print(arreglo1)
#arreglo2 = np.zeros((1,3,4,2))
#print(arreglo2.ndim)


## Funciones de Numpy para los archivos I/O
En muchos casos leer y guardar datos para procesar y trabajar en numpy es complicado usando funciones nativas de python como *open*, para procesar datos en input/output tenemos algunas funciones.
 
La función para leer texto es:

```python
loadtxt(fname, dtype=numpy.float,
 comments="#", delimiter=None, 
 converts=None, skiprows=0, 
 usecols=None, unpack=False, ndim=0)
```

La función para guardar texto es:

```python
savetxt(fname, X, fmt='%.18e', 
delimiter='', newline='\n',
header='', footer='', comments='#')
```


In [29]:
import numpy as np

#Valores dependientes

c1 = np.linspace(0,1,10)
c2 = c1**2
c3 = 2*c1
c4 = np.sin(c2)
c5 = np.cos(c3)

table = np.array([c1,c2,c3,c4,c5])

np.savetxt('datos.dat',table.T,fmt='%.6e',header='c1 \t c2 \t c3 \t c4 \t c5',footer='By: Sheryl Avendaño')

with open("datos.dat") as filedat:
  print(filedat.read())

p1,p2,p3,p4,p5 = np.loadtxt('datos.dat',unpack=True, skiprows=5)

#print('¿p1 = c1?', p1[1]==c1[1],p1[1],c1[1])
print(p1)

# c1 	 c2 	 c3 	 c4 	 c5
0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 1.000000e+00
1.111111e-01 1.234568e-02 2.222222e-01 1.234537e-02 9.754101e-01
2.222222e-01 4.938272e-02 4.444444e-01 4.936265e-02 9.028497e-01
3.333333e-01 1.111111e-01 6.666667e-01 1.108826e-01 7.858873e-01
4.444444e-01 1.975309e-01 8.888889e-01 1.962488e-01 6.302751e-01
5.555556e-01 3.086420e-01 1.111111e+00 3.037651e-01 4.436660e-01
6.666667e-01 4.444444e-01 1.333333e+00 4.299564e-01 2.352376e-01
7.777778e-01 6.049383e-01 1.555556e+00 5.687113e-01 1.524018e-02
8.888889e-01 7.901235e-01 1.777778e+00 7.104402e-01 -2.055067e-01
1.000000e+00 1.000000e+00 2.000000e+00 8.414710e-01 -4.161468e-01
# By: Sheryl Avendaño

[0.4444444 0.5555556 0.6666667 0.7777778 0.8888889 1.       ]


# **Usando algunos funciones de Numpy**

En el módulo de numpy hay una gran cantidad de funciones no sólo de álgebra lineal también de medidas estadísticas y otras. Vamos a ver algunas generales:

* [Lineal](https://numpy.org/devdocs/reference/routines.linalg.html)

* [Random](https://numpy.org/devdocs/reference/random/index.html)

* [Estadística](https://numpy.org/devdocs/reference/routines.statistics.html)

* [Métodos](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html#numpy.ndarray)

In [30]:
#Funciones random 
A = np.array(['a','b','c','d','e','f'])
print('Un arreglo de letras:',A)
print("Escoger un valor en el arreglo anterior:",np.random.choice(A))
print("Elegir un número entero entre a=0 y b=100",np.random.randint(0,100))
print("Elegir N=5 números entre 0 y 1 (dist uniforme)",np.random.rand(5))
print("Elegir N=5 números entre a=1 y b=2 (dist uniforme)",np.random.uniform(1,2,5))
print("Elegir N=7 números para media=3, desv=9 (dist normal)",np.random.normal(3,9,7))


Un arreglo de letras: ['a' 'b' 'c' 'd' 'e' 'f']
Escoger un valor en el arreglo anterior: a
Elegir un número entero entre a=0 y b=100 44
Elegir N=5 números entre 0 y 1 (dist uniforme) [0.43688527 0.49575821 0.21426124 0.70415092 0.63638594]
Elegir N=5 números entre a=1 y b=2 (dist uniforme) [1.39418442 1.57469287 1.90132883 1.80676885 1.19618528]
Elegir N=7 números para media=3, desv=9 (dist normal) [  2.37587991   3.64318594 -18.36841672   5.49857243   5.62878363
  -3.4850346  -11.39508415]


In [31]:
#Funciones álgebra lineal
A = np.matrix([[1,2.2,-3.4],[9,6,1.2],[3.2,4,-7.0]])
x = np.matrix([1,6,2])
b = np.dot(A,x.T)
print('A*x = b \n',b)
print('La solución hallada con la función es \n',np.linalg.solve(A,b))
print('La norma de x:',np.linalg.norm(x))

A*x = b 
 [[ 7.4]
 [47.4]
 [13.2]]
La solución hallada con la función es 
 [[1.]
 [6.]
 [2.]]
La norma de x: 6.4031242374328485


In [32]:
#Funciones de estadísitca
arreglo = np.random.uniform(0,10,20)
print('Promedio:',np.mean(arreglo))
print('Desviación:',np.std(arreglo))
print('Mediana:',np.median(arreglo))

Promedio: 5.29383506062809
Desviación: 2.9328895817585408
Mediana: 6.279972455645805


In [36]:
#Algunos métodos
arreglo2 = arreglo.copy()
arreglo2.sort()
print("Organizar un arreglo:",arreglo2)
print("Organizar un arreglo:",arreglo2.argsort())
print("Hallar el mínimo:",arreglo2.min())
print("Halalr el máximo:",arreglo2.max())
print("Hallar el índice del mínimo:",arreglo2.argmin())
print("Hallar el índice del máximo:",arreglo2.argmax())

Organizar un arreglo: [0.27002765 0.29208469 0.5111227  1.45324334 1.46537134 4.32333844
 4.49305162 4.55293482 5.20619905 6.01851272 6.54143219 6.62392982
 6.62973001 7.45121575 7.52950572 7.98958143 8.359056   8.40692001
 8.86754643 8.89189749]
Organizar un arreglo: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Hallar el mínimo: 0.27002764725884476
Halalr el máximo: 8.891897489569196
Hallar el índice del mínimo: 0
Hallar el índice del máximo: 19


## Ejercicios 

1.  Crea varios arreglos de diferentes tamaños con números aleatorios puede usar la distribución que [desee](https://numpy.org/devdocs/reference/random/generator.html#numpy.random.Generator)   
2. Cree una matriz cuadrada y halle su inversa con la función [adecuada](https://numpy.org/devdocs/reference/routines.linalg.html). Al usar `np.dot(A,Ainv)` revise el resultado. 

3. Revisar 3 de los métodos de los arreglos.



In [0]:
#@title Vea la solución **aquí**
#arreglo1 = np.random.beta(3,4,10)
#arreglo2 = np.random.poisson(4,(3,4))
#arreglo3 = np.random.gamma((23,1))

#A = np.random.uniform(5,10,(2,2)) 
##A = np.random.randint(-10,10,(2,2)) 
#Ainv = np.linalg.inv(A)
#np.dot(A,Ainv)

#arreglo = np.random.uniform(0,10,100)
#print("Método de la media: ",arreglo.mean())
#print("Método de redondeo: ",arreglo.round(decimals=2)[1:3])
#print("Método de reshape: ",arreglo.reshape((10,10))[1:6,1:6])

#**Operaciones Vectorizadas: Optimizaciones computacionales en los arrays de `Numpy`:**


Los arreglos multidimendsionales de `NumPy` pueden utilizarse en expresiones matemáticas para realizar cálculo utilizando las entradas de una matriz. En general, se implementan funciones matemáticas que operan sobre cada una de las entradas de la matriz. 

A continuación, realizaremos varias operaciones, a través de ejercicios corto, como:

1. Elevar al cuadrado cada elemento de una matriz dada.
2. Tomar la raiz cuadrada de cada uno de los elementos de una matriz.
3. Sumar a cada elemento de una matriz un valor dado.
4. Sumar elemento a elemento dos matrices.
5. Sumar todos los elementos de una matriz. 
6. Sumar a lo largo de una dirección los elementos de una matriz.

Cada una de estas operaciones representa una operación vectorizada.

Recordemos que los array de `NumPy` son homogéneos: **un array solo puede contener datos de un solo tipo**. Por ejemplo, una matriz puede contener enteros de 8 bits o números de coma flotante de 32 bits, pero no una mezcla de los dos. Por el contrario, las listas y tuplas de `Python` no tienen restricciones en la variedad de tipos que pueden contener; una lista dada podría contener simultáneamente cadenas, enteros y otros objetos. Esta restricción en el contenido de tipos en un array tiene un gran beneficio; al "saberse" que los contenidos de un array son homogéneos en el tipo de datos, `NumPy` puede delegar la tarea de realizar operaciones matemáticas en los contenidos de dicho arreglo a un código C compilado y optimizado. Este es un proceso que se conoce como vectorización. El resultado de esto puede ser una tremenda aceleración en relación con el cálculo análogo realizado en Python, que debe verificar minuciosamente el tipo de datos de cada uno de los elementos a medida que itera sobre las matrices, ya que Python generalmente trabaja con listas con contenido sin restricciones de en los tipos de los datos que alberga.



Empecemos definiendo una matriz cualquiera en `Python`:

In [0]:
import numpy as np

x = np.arange(0.0,9.0,1.0,dtype=float)

## Ejercicio #1
- ¿Cuales son las dimensiones de array anterior?  
- Convierta dicho array en un array de $3\times 3$ y resasignelo a la variable `x`

In [0]:
# Escriba la solución aquí.

In [0]:
#@title Solución oculta al ejercicio
print("La dimensión del array es: ", x.shape)

x = x.reshape(3,3)

print('El array de 3x3 es ', x)

La dimensión del array es:  [0. 1. 2. 3. 4. 5. 6. 7. 8.]
El array de 3x3 es  [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


## Ejercicio #2

1. Eleve cada uno de los elementos del array `x` al cuadrado y almacene el resultado en una variable `x_r2`.

2. Tome la raiz cuadrada de cada elemento del array `x` y almacene el resultado en un array de nombre `x_sqrt`

3. Sume a cada uno de los elementos `5.0` y almacene el resultado en un array x_p5.

**Nota:** No es necesario programar una función nueva o realizar ciclos for sobre el array.

In [0]:
# Escriba la solución aquí.

In [0]:
np.sqrt(x)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [0]:
#@title Solución oculta al ejercicio.

x_r2 = x**2
x_sqrt = np.sqrt(x)
x_p5 = x+5.0

print('Resultado de elevar al cuadrado cada elemento de x es \n', x_r2, '\n')
print('Resultado de tomar raiz cuadrada a cada elemento de x es \n', x_sqrt, '\n')
print('Resultado de sumar 5.0 a cada elemento de x es \n', x_p5)


Resultado de elevar al cuadrado cada elemento de x es 
 [[ 0.  1.  4.]
 [ 9. 16. 25.]
 [36. 49. 64.]] 

Resultado de tomar raiz cuadrada a cada elemento de x es 
 [[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]] 

Resultado de sumar 5.0 a cada elemento de x es 
 [[ 5.  6.  7.]
 [ 8.  9. 10.]
 [11. 12. 13.]]


## Ejercicio #3 

Defina un array de números aleatorios de tipo float de dimensiones $3\times3$, cuyos números varien entre -10 y 10, y almacénelo en una variabla `y`.





In [0]:
# Escriba la solución aquí.

In [0]:
#@title Solución oculta del ejercicio
y = np.random.uniform(low=-10, high=10, size=(3,3))

print('El resultado de y es \n', y)

El resultado de y es 
 [[-4.04018    -1.13212479  6.50452709]
 [-7.06236947 -3.95044688 -5.08958115]
 [-3.36340579 -4.34589174 -5.72017689]]


## Ejecicio #4

Realice una suma elemento a elemento de las matrices `x`e `y`. Imprima cada una de las matrices, así como el resultado de sumarlas.

In [0]:
# Escriba la solución aquí.

In [0]:
#@title Solución oculta al ejercicio

print('La matriz x es \n',x,'\n')
print('La matriz y es \n',y,'\n')
print('El resultado de sumar ambas matrices es \n',x+y)

La matriz x es 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]] 

La matriz y es 
 [[-4.04018    -1.13212479  6.50452709]
 [-7.06236947 -3.95044688 -5.08958115]
 [-3.36340579 -4.34589174 -5.72017689]] 

El resultado de sumar ambas matrices es 
 [[-4.04018    -0.13212479  8.50452709]
 [-4.06236947  0.04955312 -0.08958115]
 [ 2.63659421  2.65410826  2.27982311]]


## Ejercicio #5

Sume todos los ejercicios de la matríz `y` e imprima en pantalla el resultado.


In [0]:
# Escriba la solución aquí.

In [0]:
#@title Solución oculta al ejercicio
print('Matriz y\n',y,'\n')

print('Suma de todos los elementos de la matríz y\n',np.sum(y))

Matriz y
 [[-4.04018    -1.13212479  6.50452709]
 [-7.06236947 -3.95044688 -5.08958115]
 [-3.36340579 -4.34589174 -5.72017689]] 

Suma de todos los elementos de la matríz y
 -28.199649609336028


## Ejercicio #6

Sume todos los elementos de la matriz `y` a lo largo de las filas:


In [0]:
# Escriba la solución aquí.

In [0]:
#@title Solución oculta al ejercicio
print('Matriz y\n', y,'\n')
print('Suma de los elementos de la matriz y a lo largo de las filas \n',np.sum(y,axis=1) )

Matriz y
 [[-4.04018    -1.13212479  6.50452709]
 [-7.06236947 -3.95044688 -5.08958115]
 [-3.36340579 -4.34589174 -5.72017689]] 

Suma de los elementos de la matriz y a lo largo de las filas 
 [  1.33222231 -16.1023975  -13.42947442]


## Ejercicio #7

Defina una función en `Python` que sume los elementos de un array a lo largo de las filas y nombrela `sum_along_rows`.

In [0]:
# Escriba la solución aquí.

In [0]:
#@title Solución oculta al ejercicio
def sum_along_rows(a = np.array([[1,2],[3,4]])):
  row_sum = np.zeros(a.shape[1], dtype=float)
  for i in range(a.shape[0]):
    for j in range(a.shape[1]):
      row_sum[i] += a[i,j]
  return row_sum

print('Matriz y\n', y, '\n')
print('sum_along_rows(y)', sum_along_rows(y))


Matriz y
 [[-4.04018    -1.13212479  6.50452709]
 [-7.06236947 -3.95044688 -5.08958115]
 [-3.36340579 -4.34589174 -5.72017689]] 

sum_along_rows(y) [  1.33222231 -16.1023975  -13.42947442]


## Ejercicio #8

Defina una matriz de $10000\times10000$ elementos tipo `float` definidos entre $[-10,10]$ y almacénela en una matríz llamada `huge_matriz`.

In [0]:
# Escriba la solución aquí.

In [0]:
#@title Solución oculta al ejercicio
huge_matrix = np.random.uniform(low=-10, high=10, size=(10000,10000))

print('huge_matrix\n', huge_matrix)

huge_matrix
 [[-4.85546322 -2.46002495  8.19606624 ...  5.88101556 -9.0069324
   9.99657134]
 [ 3.37828363  6.04517966 -1.66331306 ...  0.16203508 -1.32606589
  -0.54820299]
 [ 8.30429227  5.76244483  2.63881985 ...  0.88351474  3.58843466
  -8.77748121]
 ...
 [-7.77864646 -8.85382542 -3.70462607 ...  3.40263865  6.18879203
  -2.47086771]
 [-9.10825194 -5.37683371 -9.23689555 ... -5.26133981  5.26322323
  -9.78658057]
 [-3.44396783  8.30010446 -7.40828912 ...  2.7549877   5.57476664
  -3.13706292]]


Importemos el modulo `time` para medir los tiempos de ejecución de las operacion vectorizada de suma a lo largo de las filas `np.sum(array,axis=1)` y la función programada en `Python` `sum_along_rows()`.

In [0]:
import time

Para medir los tiempos de cada programa, ejecute la estructura



```
start_time = time.time()
# En esta línea va el programa a ejecutar
exec_time = time.time() - start_time
print("--- %s segundos --- \n" % exe_time)
```



## Ejercicio #9

Mida el tiempo de ejecución de la función vectorizada `np.sum(array,axis=1)`, aplicada a `huge_matrix()`. Guarde el tiempo de ejecución en una variable `exec_time_vectorized`.

In [0]:
# Escriba la solución aquí.

In [0]:
#@title Solución oculta al ejercicio
start_time = time.time()
np.sum(huge_matrix, axis=1)
exec_time_vectorized = time.time() - start_time
print("--- %s segundos ---" %exec_time_vectorized)

--- 0.07714533805847168 segundos ---


## Ejercicio #10

Mida el tiempo de ejecución de la función `sum_along_rows()`, aplicada a huge_matrix(). Guarde el tiempo de ejecución en una variable `exec_time_python`.

In [0]:
# Escriba la solución aquí.

In [0]:
#@title Solución oculta al ejercicio
start_time = time.time()
sum_along_rows(huge_matrix)
exec_time_python = (time.time() - start_time)
print("--- %s segundos ---" % exec_time_python)

--- 53.43715524673462 segundos ---


## Ejercicio #11

Cuantas veces es más rápida la función vectorizada `np.sum()` que la función de `python` `sum_along_rows`

In [0]:
# Escriba la solución aquí.

In [0]:
#@title Solución oculta al ejercicio.
print("La función vectorizada es %f más rápida.\nINCREIBLE LO LENTO QUE ES PYTHON!" %(exec_time_python/exec_time_vectorized))

La función vectorizada es 692.681588 más rápida.
INCREIBLE LO LENTO QUE ES PYTHON!


Algunas funciones vectorizadas más se ejemplifican a continuación:

In [0]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Producto entre vectores
print("Producto vector-vector",v.dot(w))
print("Producto vector-vector", np.dot(v, w),"\n")

# Producto matriz/vector;
print("Producto matriz/vector \n",x.dot(v))
print("Producto matriz/vector \n", np.dot(x, v),"\n")

# Producto matrix/matrix ; 
print("Producto matriz/matriz \n",x.dot(y),"\n")
print("Producto matriz/matriz \n",np.dot(x, y))

Producto vector-vector 219
Producto vector-vector 219 

Producto matriz/vector 
 [29 67]
Producto matriz/vector 
 [29 67] 

Producto matriz/matriz 
 [[19 22]
 [43 50]] 

Producto matriz/matriz 
 [[19 22]
 [43 50]]


In [0]:
x = np.arange(1,5)
print(x)

# Operadores aritméticos
print('x+2 ',np.add(x,2))
print('x-2 ',np.subtract(x,2))
print('-x ',np.negative(x))
print('x*2 ',np.multiply(x,2))
print('x/2 ',np.divide(x,2))
print('x^2 ',np.power(x,2))

# Funciones trigonométricas
theta = np.linspace(0,np.pi,3)

print('sin(theta)',np.sin(theta))
print('cos(theta)',np.cos(theta))

# Exponenciales y logaritmos
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

[1 2 3 4]
x+2  [3 4 5 6]
x-2  [-1  0  1  2]
-x  [-1 -2 -3 -4]
x*2  [2 4 6 8]
x/2  [0.5 1.  1.5 2. ]
x^2  [ 1  4  9 16]
sin(theta) [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) [ 1.000000e+00  6.123234e-17 -1.000000e+00]
e^x = [ 2.71828183  7.3890561  20.08553692 54.59815003]
2^x = [ 2.  4.  8. 16.]
3^x = [ 3  9 27 81]
ln(x) = [0.         0.69314718 1.09861229 1.38629436]
log2(x) = [0.        1.        1.5849625 2.       ]
log10(x) = [0.         0.30103    0.47712125 0.60205999]


#**Carga y Lectura de un archivo**

Constantemente se hará necesario trabajar con archivos desde un notebook, para hacerlo desde Colab miraremos el proceso.


In [0]:
# Carga el Drive
from google.colab import drive

# Esto solicitará autorización.
#drive.mount('/content/drive', force_remount=True)

Leamos entonces un archivo `.cvs` estos archivos suelen poderse leer en una hoja de cálculo como excel, o bien en un archivo de texto plano como block de notas. Puede pensar en él como una hoja de Excel.

El siguiente archivo se llama `mpg.cvs` y contiene datos económicos de combustible para 234 automóviles tales como:

* mpg : millas por galón
* class : clasificación de el carro
* cty : mpg en ciudad
* cyl : # de cilindros
* displ : desplazamiento del motor en litros
* drv : f = tracción delantera, r = tracción trasera, 4 = 4wd
* fl : combustible (e = etanol E85, d = diesel, r = regular, p = premium, c = GNC)
* hwy : mpg en carretera
* manufacturer : fabricante de automóviles
* model : codelo del carro
* trans : tipo de transmisión
* year : año del modelo

Puede descargar el archivo [mpg.cvs](https://github.com/diplomado-bigdata-machinelearning-udea/curso0/blob/master/S06/mpg.csv) y cargarlo a su drive

In [0]:
import csv #permite usar archivos cvs
%precision 2

try:
  with open('/content/drive/My Drive/mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile)) #Revise bien la dirección en la que cargó el archivo
except:
  print("Revise bien la dirección en la que cargó el archivo")
else:
  mpg[:3] # The first three dictionaries in our list.

Revise bien la dirección en la que cargó el archivo


También, siempre que el archivo sea público (lo cual no es siempre es el caso) puede cargarlo directamente desde la dirección web:

In [0]:
from urllib.request import urlopen
path_csv ="https://raw.githubusercontent.com/diplomado-bigdata-machinelearning-udea/curso0/master/S06/mpg.csv" 

with urlopen(path_csv) as response:
  try:
    content =  response.read().decode(response.headers.get_content_charset())
  except Exception as err:
    print("Error:",err)
  else:
    with open("mpg.csv","w") as csvfile: 
      csvfile.write(content)

try:
  with open("mpg.csv") as csvfile:
    mpg = list(csv.DictReader(csvfile)) #Revise bien la dirección en la que cargó el archivo
except:
  print("Revise bien que se cargó el archivo")
else:
  print(mpg[:3]) # The first three dictionaries in our list.



[OrderedDict([('', '1'), ('manufacturer', 'audi'), ('model', 'a4'), ('displ', '1.8'), ('year', '1999'), ('cyl', '4'), ('trans', 'auto(l5)'), ('drv', 'f'), ('cty', '18'), ('hwy', '29'), ('fl', 'p'), ('class', 'compact')]), OrderedDict([('', '2'), ('manufacturer', 'audi'), ('model', 'a4'), ('displ', '1.8'), ('year', '1999'), ('cyl', '4'), ('trans', 'manual(m5)'), ('drv', 'f'), ('cty', '21'), ('hwy', '29'), ('fl', 'p'), ('class', 'compact')]), OrderedDict([('', '3'), ('manufacturer', 'audi'), ('model', 'a4'), ('displ', '2'), ('year', '2008'), ('cyl', '4'), ('trans', 'manual(m6)'), ('drv', 'f'), ('cty', '20'), ('hwy', '31'), ('fl', 'p'), ('class', 'compact')])]


`csv.Dictreader` ha leído en cada fila de nuestro archivo csv como un diccionario. `len` muestra que nuestra lista está compuesta por 234 diccionarios.

In [0]:
len(mpg)

`keys` nos da los nombres de columna de nuestro csv.

Si quisiéramos hayar el promedio de las millas por galón en ciudad podríamos

In [0]:
sum(float(d['cty']) for d in mpg) / len(mpg)

Use `set` para devolver los valores únicos para la cantidad de cilindros que tienen los autos en nuestro conjunto de datos.

In [0]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

Aquí hay un ejemplo más complejo en el que estamos agrupando los autos por número de cilindros y encontrando el promedio de mpg en ciudad para cada grupo.

In [0]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl

#**Pandas**

Pandas es un módulo que fue creado en 2008 por Wes McKinney, es un proyecto Open Source con una licencia muy permisiva, tiene una comunidad bastante amplia con más de 100 desarrolladores de código que día a día lo hacen mejor. Pandas es una de las librerías más usadas hoy por hoy en lo que respecta a Data science. En estas sesiones intentaremos abordar un poco lo que respecta a Pandas, sin embargo si lo desea se recomienda pasar por "Python for Data Analysis" escrito por Wes McKinney y publicado por la editorian O'Reilly.


In [0]:
import pandas as pd

##Series
Las series de pandas son una de las estructuras centrales en para Pandas. Puede pensarlas como un cruce entre una lista y un diccionario. Los items son guardados en orden y hay etiquetas con las cuales se puede recuperar los items.

![alt text](https://github.com/tomasate/Curso0/blob/master/Captura2.PNG?raw=true)

Una forma de visualizarlo es como 2 columnas de datos, el primero es un índice especial, tal y como el `key` de un diccionario y el segundo son los datos.
Notemos que la columna de los datos tiene una etiqueta por sí misma, y puede consultarse usando el atributo `.name` esto es diferente que con los diccionarios, y es bastante útil a la hora de mezclar diferentes tablas de datos.

Por ahora intentemos crear una serie nosotros.

In [0]:
animals = ['Tiger', 'Bear', 'Moose']
pd.Series(animals)

In [0]:
numbers = [1, 2, 3]
pd.Series(numbers)

Pandas usa por debajo el módulo numpy por lo que permite usar objetos como `None` en caso de querer evitar llenar un espacio en el caso de strings. En el caso de números automáticamente crea una variable de tipo float llamada `NaN`

In [0]:
animals = ['Tiger', 'Bear', None]
pd.Series(animals)

In [0]:
numbers = [1, 2, None]
pd.Series(numbers)

También es posible hacer una serie a partir de diccionarios en lugar de listas, en este caso el `key` se convierte en nuestro índice

In [0]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

In [0]:
s.index

También podemos hacer la lista de los datos y pasar el índice por separado como otra lista.

In [0]:
s = pd.Series(['Tiger', 'Bear', 'Moose'], index=['India', 'America', 'Canada'])
s

###Consultar una serie
Es posible consultar en una serie bien sea por la posición del índice o bien por la etiqueta del índice. Para consultar por valor numérico, empezando por cero utilizamos el atributo `.iloc[]` para consultar por la etiqueta del índice usamos el atributo `.loc[]`


In [0]:
sports = {'Archery': 'Bhutan',
          'Golf': 'Scotland',
          'Sumo': 'Japan',
          'Taekwondo': 'South Korea'}
s = pd.Series(sports)
s

In [0]:
s.iloc[3]

In [0]:
s.loc['Taekwondo']

Pandas está diseñado de una forma tal que sea amigable buscar este tipo de objetos por el operador indexación, por lo que si buscamos `s[i]` con `i` siendo un número, él interpreta de forma subyacente lo que sería el operador `iloc`.

In [0]:
s[3]

In [0]:
s['Golf']

Sin embargo hay que tener cuidado cuando por ejemplo se usen números como índices, pues no necesariamente el índice debe coincidir con la etiqueta, por lo que siempre es mejor usar los atributos.

In [0]:
sports = {99: 'Bhutan',
          100: 'Scotland',
          101: 'Japan',
          102: 'South Korea'}
s = pd.Series(sports)
s[0]

In [0]:
s.iloc[0]

Consideremos una tarea simpleque implique tener en cuenta todos los valores dentro de una serie, y operar con ellos, esto puede ser encontrar un cierto número, resumir datos, o transformarlos de alguna forma. Una aproximación típica a esto es la iteración sobre todos los items de la serie e invocar la operación que nos interesa, por ejemplo, creemos una serie de floats que bien podrían ser precios para ciertos productos.

In [0]:
s = pd.Series([100.00, 120.00, 101.00, 3.00])
s

In [0]:
total = 0
for item in s:
    total+=item
print(total)

O bien podríamos usar lo que sabemos sobre vectorización

In [0]:
import numpy as np

total = np.sum(s)
print(total)

Comprobemos cuál de los 2 métodos es mejor:

In [0]:
#Creamos una serie de 10000 números enteros entre 0 y 1000 
s = pd.Series(np.random.randint(0,1000,10000))
s.head()

Usemos la funcion `timeit` que correrá nuestro código un par de veces y nos dirá qué tanto tiempo tarda en ejecutarlo

In [0]:
%%timeit -n 100
summary = 0
for item in s:
    summary+=item

In [0]:
%%timeit -n 100
summary = np.sum(s)

Aplica algo similar para el caso en el que deseamos modificar los datos de la serie

In [0]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
for label, value in s.iteritems():
    s.loc[label]= value+2

In [0]:
%%timeit -n 10
s = pd.Series(np.random.randint(0,1000,10000))
s+=2


Podemos agregar un nuevo item a nuestra serie de la siguiente forma

In [0]:
s = pd.Series([1, 2, 3])
s.loc['Animal'] = 'Bears'
s

Hasta ahora hemos visto ejemplos en los que el índice de los datos es único, veamos un ejemplo en el cual los índices NO son únicos, lo cual hace de las seriesun objeto fundamentalmente diferente a las bases de datos que suelen encontrarse frecuentemente.


In [0]:
original_sports = pd.Series({'Archery': 'Bhutan',
                             'Golf': 'Scotland',
                             'Sumo': 'Japan',
                             'Taekwondo': 'South Korea'})
cricket_loving_countries = pd.Series(['Australia',
                                      'Barbados',
                                      'Pakistan',
                                      'England'], 
                                   index=['Cricket',
                                          'Cricket',
                                          'Cricket',
                                          'Cricket'])
all_countries = original_sports.append(cricket_loving_countries)
original_sports.append(cricket_loving_countries)

In [0]:
original_sports

Note que la serie original_sports no fue modificada.

In [0]:
all_countries

Ahora para consltar los paises cuyo deporte es el cricket:


In [0]:
all_countries.loc['Cricket']

##Data Frame o Cuadro de Datos
El data frame es una estructura de datos que podría bien ser considerada el corazón de el módulo de Pandas. Es el objeto primario con el cual un analista de datos en python puede encontrarse trabajando.
Uno puede pensar en un data frame como una serie dos dimensional, donde tenemos un índice y múltiples columnas, donde cada columna tendrá una etiqueta. De hecho la distinción entre una columna. De hecho uno puede pesar que la diferencia entre una columna y una fila es solo conceptual, lo que haría de un Data frame una suerte de arreglo 2 dimensional.

Existen multiples formas de hacer un data frame, podemos usar un grupo de series, donde cada representaría una fila de datos. También podríamos usar diccionarios

In [0]:
purchase_1 = pd.Series({'Nombre': 'Tomas',
                        'Objeto Comprado': 'Comida para perro',
                        'Precio': 22.50})
purchase_2 = pd.Series({'Nombre': 'Sheryl',
                        'Objeto Comprado': 'Arena de gatos',
                        'Precio': 12.50})
purchase_3 = pd.Series({'Nombre': 'Sebastian',
                        'Objeto Comprado': 'Semillas para ave',
                        'Precio': 5.00})
df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Tienda 1', 'Tienda 1', 'Tienda 2'])
df.head()

Similar a las series podemos extraer información usando los tributos `loc` y `iloc`sin enmbargo en este caso como el data frame es 2 dimensional nos entregará información 2 dimensional (en ocasiones 1 dimensional), es decir un data frame (o una serie)

In [0]:
df.loc['Tienda 1']

In [0]:
df.loc['Tienda 2']

Algo es el hacer una transposición del data frame, es decir cambiar las filas por las columnas

In [0]:
df.T

Ahora supongamos que estamos interesados en ver los precios en nuestro data frame

In [0]:
df['Precio']

Inclusive si quisieramos ver los costos de la tienda número 1 tendríamos.

In [0]:
df.loc['Tienda 1']['Precio']

Esto último sería encadenar operadores de indexación y es muy útil a la hora de hacer consultas. Es importante tener en cuenta que esto termina por mostrar una copia del data frame, diferente a una vista del data frame. Esto es algo a considerar si estoy modificando mis datos.

Podemos presentar además solo las columnas que deseamos de la siguiente forma

In [0]:
df.loc[:,['Nombre', 'Precio']]

Veamos cómo podemos eliminar información de un data frame

In [0]:
df.drop('Tienda 1')

Lo anterior no ha cambiado nuestro data frame

In [0]:
df

Lo mejor es hacer una copia con la modificación

In [0]:
copy_df = df.copy()
copy_df = copy_df.drop('Tienda 1')
copy_df 

Finalmente podríamos agregaruna nueva columna

In [0]:
df['Location'] = None
df

##Ejercicio 1
Haremos un ejercicio sobre Covid, con un archivo `.csv` [Covid-19.csv](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-17-2020.csv).
La idea es hacer un DataFrame con los casos confirmados que aparecen como `Confirmed`, las muertes como `Deaths` y los recuperados como `Recovered`. Además calcule los Casos activos por Pais o region `Country/Region` de forma vectorizada y finalmente muestre ÚNICAMENTE estos datos. 
Hint: utilice `pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-17-2020.csv')` para leer el archivo csv con Pandas.

Puede ver la solución **acá**
<!---
import pandas as pd
covid_data= pd.read_csv('https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/03-17-2020.csv')
covid_data['Active'] = covid_data['Confirmed'] - covid_data['Deaths'] - covid_data['Recovered']

df = pd.DataFrame([covid_data['Country/Region'],covid_data['Confirmed'], covid_data['Deaths'], covid_data['Recovered'], covid_data['Active']])
df.T.head()
--->